#@ load("@ytt:data","data")
#@ load("@ytt:base64","base64")
#@ load("@ytt:yaml", "yaml")

---
apiVersion: v1
kind: Secret
metadata:
  name: cf-values
data:
  cf-values.yaml: #@ base64.encode(yaml.encode(data.values))
